### ISSUE TITLE
NHS footer is not shown correclty

### ISSUE THREAD

**Issue by nickbaf** [buseolafusca/mhs-mental-health-system-mobile#29]
Need to add overflow

**Comment by nickbaf** [comment]
@Moiravan Did you push your changes? I remember you fixed this!

**Comment by Moiravan** [comment]
@nickbafJust pushed on resources branch, haven't merge yet

**Comment by nickbaf** [comment]
Cool, tnx.

**Comment by nickbaf** [comment]
Thanks Yiming
